### INSCRIPCION - LISTAR
GET http://localhost:5002/inscripciones



### INSCRIPCION - CREAR
POST http://localhost:5002/inscripciones
Content-Type: application/json

{
  "idUsuario": 19,
  "idCurso": 1,
  "pagoInscripcion": "PAGADO",
  "cuponDescuento": "DESC10"
}



### INSCRIPCION - BUSCAR POR ID INSCRIPCION
GET http://localhost:5002/inscripciones/1


### INSCRIPCION - ACTUALIZAR
PUT http://localhost:5002/inscripciones/2
Content-Type: application/json

{
  "idUsuario": 19,
  "idCurso": 1,
  "pagoInscripcion": "No pagado",
  "cuponDescuento": "NINGUNO"
}


### INSCRIPCION - ELIMINAR
DELETE http://localhost:5002/inscripciones/3
