### PROGRESO - LISTAR
GET http://localhost:5003/progresos


### PROGRESO - CREAR
POST http://localhost:5003/progresos
Content-Type: application/json

{
  "idUsuario": 19,
  "progresoEstudiante": "45.5",
  "evaluacion": "EN_PROGRESO"
}


### PROGRESO - BUSCAR POR ID
GET http://localhost:5003/progresos/1


### PROGRESO - ACTUALIZAR
PUT http://localhost:5003/progresos/1
Content-Type: application/json

{
  "idUsuario": 1,
  "progresoEstudiante": "80.0",
  "evaluacion": "COMPLETADO"
}


### PROGRESO - ELIMINAR
DELETE http://localhost:5003/progresos/2